spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5435/keycloak
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/Oauth

keycloak.server-url=http://localhost:9090
keycloak.realm=Oauth
keycloak.client-id=auth-service-client
keycloak.client-secret=secret

keycloak.token-url=${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect"
services.user-service.name=user-service
services.user-service.url=http://localhost:8081
