spring.application.name=${APP_NAME}
services.user-service.url=${USER_SERVICE_URL}
services.user-service.name=${USER_SERVICE_NAME}


keycloak.server-url=http://localhost:${KEYCLOAK_EXTERNAL_PORT}
keycloak.realm=${KEYCLOAK_REALM}
keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}





